version: '3.6'

services:

   nginx:
#     build: ./nginx
     image: passwork/nginx
     container_name: nginx
     networks:
       - passwork
     depends_on:
            - "php8"
            - "db"

   db:
#     build: ./mongo
     image: passwork/mongodb
     container_name: db
     networks:
       - passwork

#   php:
#     build: ./php-fpm
#     image: passwork/php-fpm
#     container_name: php
#     networks:
#       - passwork

   php8:
     build: ./php8-fpm
     image: passwork/php8-fpm
     container_name: php8
     networks:
       - passwork

   postfix:
#     build: ./postfix
     image: passwork/postfix
     container_name: postfix     
     networks:
       - passwork
     depends_on:
            - "nginx"

networks:
  passwork:
    driver: bridge
